dataset: 'doremi'
labels_to_use: '7_labels'
position_as_bounding_box: False
n_neighbors_KNN: 13
prefilter_KNN: True
normalize_positions: True
seed: 123
learning_rate: 1
load_model: false
start_from_best_model: True
scheduler_factor: 0.5
scheduler_patience: 10
undirected_edges: False
jump_back_on_lr_change: True
layer_type: 'graphSAGE'
batch_size: 64
weight_imbalance: -1
n_epochs: 100
visualize_first_score: True
save_model: True
